FROM python:3
RUN 
WORKDIR /app
COPY accounts accounts
COPY attendees attendees
COPY common common
COPY conference_go conference_go
COPY events events
COPY presentations presentations
COPY requirements.txt requirements.txt
COPY manage.py manage.py
RUN pip install -r requirements.txt
CMD gunicorn conference_gowsgi